# .github/workflows/lint-check.yml
name: Lint & Type Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Run Black, Ruff, Pyright
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv pip install --system marimo matplotlib numpy

      - name: Install Python tools
        run: |
          uv pip install --system pre-commit black pyright ruff

      - name: Run pre-commit checks
        run: pre-commit run --all-files
